"""change_cocktail_ingredient_amount_to_integer

Revision ID: 3c60abac42be
Revises: eaf14a1ae534
Create Date: 2025-05-21 23:09:14.902690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c60abac42be'
down_revision: Union[str, None] = 'eaf14a1ae534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
